src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(
     *     min=10,
     *     max=255,
     *     minMessage="Le titre de l'article doit avoir plus de 10 caractères")
     */
    private $Title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="text")
     */
    private $Content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="articles")
     */
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->CreatedAt;
    }

    public function setCreatedAt(\DateTimeInterface $CreatedAt): self
    {
        $this->CreatedAt = $CreatedAt;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Article::class, mappedBy="category")
     */
    private $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Article[]
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setCategory($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getCategory() === $this) {
                $article->setCategory(null);
            }
        }

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Title')
            ->add('Description')
            ->add('Content')
            ->add('Category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'title'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Form/CatType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class CatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Title')
            ->add('Description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Category;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\ArticleType;
use App\Form\CatType;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function home(): Response
    {
        return $this->render('home/index.html.twig');
    }

    /**
     * @Route("/articles", name="articles")
     */
    public function articles(): Response
    {
        $repo = $this->getDoctrine()->getRepository(Article::class);
        $articles = $repo->findAll();

        return $this->render('home/articles.html.twig', ["articles" => $articles]);
    }

    /**
     * @Route("/article/{id}", name="article_detail")
     */
    public function article(Article $article): Response
    {
        return $this->render('home/article_detail.html.twig', [
            "article" => $article
            ]);
    }

    /**
     * @Route("/ajouter-article", name="new_article")
     * @Route("/edit-article/{id}", name="article_edit")
     */
    public function new_edit_article(Article $article = null, Request $request, ObjectManager $manager): Response
    {
        if (!$article) {
            $article = new Article();
        }
        
        $form = $this->createForm(ArticleType::class, $article);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            if (!$article->getId()) {
                $article->setCreatedAt(new \DateTime());
            }
    
            $manager->persist($article);
            $manager->flush();
    
            return $this->redirectToRoute('article_detail', [
                "id" => $article->getId()
            ]);
        }

        return $this->render('home/new_article.html.twig', [
            'form' => $form->createView(),
            'editMode' => $article->getId() !== null
        ]);
    }   
    
    /**
     * @Route("/nouvelle-categorie", name="new_cat")
     * @Route("/edit-category/{id}", name="cat_edit")
     */
    public function new_cat(Category $category = null, Request $request, ObjectManager $manager): Response
    {
        if (!$category) {
            $category = new Category();
        }
        
        $form = $this->createForm(CatType::class, $category);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
    
            $manager->persist($category);
            $manager->flush();
    
            return $this->redirectToRoute('cat_detail', [
                "id" => $category->getId()
            ]);
        }

        return $this->render('home/new_cat.html.twig', [
            'form' => $form->createView(),
            'editMode' => $category->getId() !== null
        ]);
    }

    /**
     * @Route("/category/{id}", name="cat_detail")
     */
    public function detailcat(Category $category): Response
    {
        return $this->render('home/cat_detail.html.twig', [
            "category" => $category
            ]);
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
          <a class="navbar-brand" href="{{path('home')}}">Chat Pito !</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{{path('articles')}}">
                  Article
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{path('new_article')}}">
                  Créer un article
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{path('new_cat')}}">
                  Créer une catégorie
                </a>
              </li>
            </ul>
          </div>
        </nav>
    <div class="container">

        {% block body %}{% endblock %}

    </div>
    </body>
</html>

templates/home/article_detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<article>
					<h2 class="article__titre">{{ article.title }}</h2>
					<p class="category__titre">{{ article.category.title }}</p>
					<p class="artcle__date">Date de l'article: {{ article.createdAt | date('d/m/Y') }} à {{ article.createdAt | date('H:i') }}</p>
					<p class="article__description">{{ article.description }}</p>
					<p>{{ article.content }}</p>
					<a href="{{ path('article_edit', {'id': article.id}) }}" class="btn btn-danger">Edit</a>
				</article>
			</div>
		</div>
	</div>
{% endblock %}

templates/home/articles.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container">
	<p>la classe des articles...</p>
		<div class="row">
			<div class="col-md-9">
				<h1>Je suis un grand titre</h1>
				{% for article in articles %}
					<article>
						<h2 class="article__titre">{{ article.title }}</h2>
						<p class="category__titre">Categorie : {{ article.category.title }}</p>
						<p class="artcle__date">Date de l'article: {{ article.createdAt | date('d/m/Y') }} à {{ article.createdAt | date('H:i') }}</p>
						<p class="article__description">{{ article.description }}</p>
						<p>{{ article.content }}</p>
						<a class="btn btn-success article__button" href="{{ path('article_detail', {'id': article.id}) }}">En savoir plus</a>
					</article>
				{% endfor %}
			</div>
			<aside class="col-md-3">
				<h2>Categorie</h2>
				{% for article in articles %}
					<a class="btn btn-outline-dark category__titre " href="{{ path('cat_detail', {'id': article.category.id}) }}">{{ article.category.title }}</a>
					<p class="category__titre"></p>
				{% endfor %}
			</aside>
		</div>
	</div>
{% endblock %}

templates/home/cat_detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-md-9">
				<article>
					<h2 class="category__titre">{{ category.title }}</h2>
					<p class="article__description">{{ category.description }}</p>
					<a href="{{ path('cat_edit', {'id': category.id}) }}" class="btn btn-danger">Edit</a>
				</article>
			</div>
			<aside class="col-md-3">
				<h4>Articles liés à cette catégorie</h4>
				{% for article in category.articles %}
					<a href="{{ path('article_detail', {'id': article.id}) }}">
						{{ article.category.title }}<br>
					</a>
				{% endfor %}
			</aside>
		</div>
	</div>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<p>Home</p><br>

{% endblock %}

templates/home/new_article.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>{% block title %}Ajouter un Article{% endblock %}</h1><br>

    <div class="container">
        <div class="col-md-12">
            {{ form_start(form) }}
                {{ form_row(form.Title, {'attr': {'placeholder': "Titre de l'article"}}) }}
                {{ form_row(form.Description, {'attr': {'placeholder': "Petite description de l'article"}}) }}
                {{ form_row(form.Content, {'attr': {'placeholder': "Contenu de l'article"}}) }}
                {% if editMode %}
                    <button type="submit" class="btn btn-danger">
                        modifier l'article
                    </button>
                {% else %}
                    <button type="submit" class="btn btn-danger">
                        Générer l'article
                    </button>
                {% endif %}
                {{ form_row(form.Category, {'attr': {'placeholder': "Nom de la Catégorie"}}) }}

                
            {{ form_end(form) }}
            
        </div>
    </div>


{% endblock %}

templates/home/new_cat.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>{% block title %}Ajouter une Catgeorie{% endblock %}</h1><br>

    <div class="container">
        <div class="col-md-12">
            {{ form_start(form) }}
                {{ form_row(form.Title, {'attr': {'placeholder': "Titre de le la catégorie"}}) }}
                {{ form_row(form.Description, {'attr': {'placeholder': "Petite description de la catégorie"}}) }}
                
                {% if editMode %}
                    <button type="submit" class="btn btn-danger">
                        Modifier la category
                    </button>
                {% else %}
                    <button type="submit" class="btn btn-danger">
                        Générer la category
                    </button>
                {% endif %}

            {{ form_end(form) }}
            
        </div>
    </div>

{% endblock %}